ministryofjustice/hmpps-github-actions

.github/workflows/security_npm_dependency.yml, .github/workflows/security_npm_outdated.yml
As identified by Andy Lee - the built in version of node doesn't run properly against typescript projects.
This gives the benefit of running a specific version. Validated on my test project (and with the node -v and npm -v responses)
=> fix: now uses inputs node_version to determine the version of node

.github/workflows/security_veracode_policy_scan.yml
Currently all but the first veracode policy scan will fail because the scan is being sent with the github ref (ref/main) which already exists on subsequent scans.
This fixes it by using the run_id
=> use the run_id rather than ref to prevent duplication failure

.github/workflows/security_trivy.yml
This enables caching of the vulnerability DB by default to mitigate the `429 TOOMANYREQUESTS` errors.
=> Bump Trivy Action to v0.28.0

.github/workflows/security_trivy.yml
with fallback to GHCR, should help mitigate rate-limiting issues
=> Add ECR repository for Trivy scans

templates/workflows/security_trivy.yml
This job is common for both typescript and kotlin projects, and should be named appropriately
=> Update name of the `security_trivy` job

.github/actions/build-test-and-deploy/cloud-platform-deploy/action.yml, .github/actions/slack_release_results/action.yml, .github/actions/version_history/action.yml, .github/workflows/deploy_env.yml, renovate.json
Improves the slack message to include commit history in the same way as the existing CircleCI process runs.
This also includes the first line of the commit message to prevent failure of slack messages if it's a multiline message (HEAT-467)
This also covers HEAT-431
=> HEAT-422 commit history

.github/actions/build-test-and-deploy/cloud-platform-deploy/action.yml, .github/workflows/deploy_env.yml
Matt's done the hard work of deploying the values to org variable - this includes the two variables in the `./ip-allowlist-groups.yaml` file (in the case of the allowlist) and the `generic-service.allowlist_version` variable.
I've managed to deploy to james-kotlin-test with the parameters, but still looking to validate.
=> HEAT-491: IP allowlists - add provision for IP allowlist using org variables

.github/actions/build-test-and-deploy/build_docker/action.yml
- Add optional `tag_latest` input to the `build_docker` action to allow building and publishing an image, without making it `latest`
- Defaults to `true` to not break any existing use. Overriding value with `false` will stop the image getting the latest tag
=> Add  optional `tag_latest` input  to `build_docker` action

.github/actions/build-test-and-deploy/build_docker/action.yml, .github/actions/build-test-and-deploy/build_multiplatform_docker/action.yml, .github/workflows/docker_build.yml
- Add optional tag_latest input to the build_docker action to allow building and publishing an image, without making it latest
- Defaults to true to not break any existing use. Overriding value with false will stop the image getting the latest tag
- **(New)** Creates list of docker tags to apply in a step before building/publishing image
- **(New)** Setup for both build_docker and build_multiplatform_docker
=> Add optional tag_latest input to build_docker action (Attempt #2)

.github/actions/build-test-and-deploy/build_docker/action.yml, .github/workflows/docker_build.yml, .github/workflows/docker_push.yml
This PR enables the following workflow, which is currently supported by the HMPPS CircleCI Orb:
1. Build a Docker image and persist it to Artifacts instead of pushing it to a registry
2. Use the image from Artifacts to stand up a containerised test environment
3. Run end-to-end tests against that image (containerised environment)
4. If the tests pass, push the image to the registry and optionally tag it as "latest"
Example workflow can be found here: https://github.com/ministryofjustice/hmpps-assess-risks-and-needs-oastub-ui/blob/main/.github/workflows/pipeline_main.yml
=> Add the ability to upload built images to artifacts and publish them at a later stage

.github/actions/slack_release_results/action.yml
This uses Python to parse the commit message so it's a bit safer to be sent to Slack
=> bug/HEAT-589 sanitise commit messages for use in Slack

.github/workflows/security_codeql_actions.yml, templates/workflows/security_npm_dependency.yml, templates/workflows/security_owasp.yml, templates/workflows/security_trivy.yml, templates/workflows/security_veracode_pipeline_scan.yml, templates/workflows/security_veracode_policy_scan.yml
This adds a CodeQL scan to github actions for Github actions within a repository, which gets added to the Security Code Scanning section of a repo.
Once this is in place, I'll implement it for the Portfolio Management projects to shake down the various actions..
Also adds the requisite permissions to the template scans
=> feat/HEAT-592 GitHub actions scans

.github/workflows/gradle_localstack_postgres_verify.yml, .github/workflows/gradle_localstack_verify.yml, .github/workflows/gradle_postgres_verify.yml, .github/workflows/gradle_verify.yml
New gradle workflows that do the following:
1. Default the java options to empty string - haven't needed to set this since moving to github actions anyway
2. Uses [gradle/actions/setup-gradle](https://github.com/gradle/actions) to setup gradle, validate the wrapper and configure cache settings
3. Allow `gradle-command` to be overridden by calling jobs
4. Provide additional workflows for localstack and postgres configurations
=> SDIT-2737: 👷 Add in gradle helper workflows

.github/workflows/security_trivy.yml
Currently this is set to ignore_unfixed= 'true' by default - I'll validate with the template repos once this is tagged.
=> Include options for trivy scans so that we can report on unfixed vulnerabilities

.github/workflows/deploy_env.yml
Tiny change to support envs named "production" in addition to "prod".
=> Support prod envs named 'production'

.github/workflows/security_veracode_pipeline_scan.yml, .github/workflows/security_veracode_policy_scan.yml
This backward compatible change introduces the ability to provide an optional `veracode_package_artifact_name` argument to the veracode scan workflows, allowing applications different to kotlin/typescript, for instance Rails, to package their source code themselves, store it as an artifact, and the veracode workflow will download and use this artifact, instead of using the `security_veracode_prepare_artifacts` action, which is not compatible with some languages like Rails that require a specific packaging process.
Pipeline scan:
https://github.com/ministryofjustice/hmpps-complexity-of-need/actions/runs/15276369612
Policy scan:
https://github.com/ministryofjustice/hmpps-complexity-of-need/actions/runs/15276369650
=> Support for pre-packaged veracode source code

docs/workflow-migration.md
**WHAT**
This PR adds a few lines, and a link to GitHub's own documentation,
relating to the manual approval / review of PRs for deployment.
I added in the word `manual`, to make this information more
findable.
I specified the exact location of the settings being referred to.
**WHY**
As someone with limited experience of CI/CD at scale with GitHub
Actions, I found the initial documentation unclear, and difficult to
find (I wasn't searching for "approval gate").  This was largely because
I did not know what I was searching for.
After fixing my problem with my team, I wanted to update the docs to
help future tech folks find the information, and provide them with more
specific information.
=> Docs: Clarifying information about approval gating

.github/workflows/security_owasp.yml, kotlin-to-nvd2.bash
- Extra OWASP job added for when `nvd_feed_version=2` 
- This only runs on ministryofjustice/ repositories
Note: this needs changes to be made to `build.gradle.kts` in the local project directory. To assist with this, I've made a script - kotlin-to-nvd2.bash - that does the appropriate configuration in the local repo.
Currently there are four self-hosted runners (each sharing an API key, but that's only required on build, and they are staggered) - if we need more due to queuing, we can sort that out later.
=> FEAT/HEAT-767 - self hosted runners for OWASP scans

.github/workflows/node_integration_tests.yml
This matches the established convention, i.e: `npm run test:ci`
=> Scope int-test-init to be ci specific

migrate-repo.sh, recreate-kotlin-security-jobs.bash, recreate-typescript-security-jobs.bash
This is to avoid potential conflicts when there's the default CodeQL process already in place (it will likely fail because (advanced security isn't turned on by default)
=> remove codeql scans from migration scripts
